# Write your MySQL query statement below
SELECT W1.ID 
FROM WEATHER W1 
WHERE W1.TEMPERATURE> 
(
    SELECT W2.TEMPERATURE
    FROM WEATHER W2
    WHERE W2.RECORDDATE=DATE_SUB(W1.RECORDDATE,INTERVAL 1 DAY)
)
